spring.application.name=game-view-api

spring.datasource.url=jdbc:postgresql://localhost:5432/gameview_dev
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
